// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdC17ShAarczQvjsqlpHLLoqEJjZG1lxM',
    appId: '1:451356668633:web:260f6e6d757d1dec0c44c8',
    messagingSenderId: '451356668633',
    projectId: 'habitjournalprojectfirebase',
    authDomain: 'habitjournalprojectfirebase.firebaseapp.com',
    storageBucket: 'habitjournalprojectfirebase.firebasestorage.app',
    measurementId: 'G-DYZPF5EXYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOEirE_XYVbtD7e_Ij7My3yjtwIQp5V8',
    appId: '1:451356668633:android:ad761a8e17e543820c44c8',
    messagingSenderId: '451356668633',
    projectId: 'habitjournalprojectfirebase',
    storageBucket: 'habitjournalprojectfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDhqm9RCK0qGIH8pEGqRttN_lxd-Xxdo',
    appId: '1:451356668633:ios:2f958acd657ed8210c44c8',
    messagingSenderId: '451356668633',
    projectId: 'habitjournalprojectfirebase',
    storageBucket: 'habitjournalprojectfirebase.firebasestorage.app',
    iosClientId: '451356668633-0c21fharlpqdqkqkalkrr8srf1qaba82.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChDhqm9RCK0qGIH8pEGqRttN_lxd-Xxdo',
    appId: '1:451356668633:ios:2f958acd657ed8210c44c8',
    messagingSenderId: '451356668633',
    projectId: 'habitjournalprojectfirebase',
    storageBucket: 'habitjournalprojectfirebase.firebasestorage.app',
    iosClientId: '451356668633-0c21fharlpqdqkqkalkrr8srf1qaba82.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdC17ShAarczQvjsqlpHLLoqEJjZG1lxM',
    appId: '1:451356668633:web:260f6e6d757d1dec0c44c8',
    messagingSenderId: '451356668633',
    projectId: 'habitjournalprojectfirebase',
    authDomain: 'habitjournalprojectfirebase.firebaseapp.com',
    storageBucket: 'habitjournalprojectfirebase.firebasestorage.app',
    measurementId: 'G-DYZPF5EXYY',
  );
}
