// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTln0auFrTna5CBeCwUUBhmpwNSDU-eCQ',
    appId: '1:683164694019:web:54e05b9ed86ee4b7004036',
    messagingSenderId: '683164694019',
    projectId: 'project-habit-journal',
    authDomain: 'project-habit-journal.firebaseapp.com',
    storageBucket: 'project-habit-journal.firebasestorage.app',
    measurementId: 'G-89KE51KQSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn64yRI8pqWrE9Datu0QyghIts33tfx1A',
    appId: '1:683164694019:android:5c0ce6bacf10809f004036',
    messagingSenderId: '683164694019',
    projectId: 'project-habit-journal',
    storageBucket: 'project-habit-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALul6bQhbCryPI1lZhAWbT92jQSkAotU4',
    appId: '1:683164694019:ios:c300904c9dfe1897004036',
    messagingSenderId: '683164694019',
    projectId: 'project-habit-journal',
    storageBucket: 'project-habit-journal.firebasestorage.app',
    iosBundleId: 'com.example.habitJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALul6bQhbCryPI1lZhAWbT92jQSkAotU4',
    appId: '1:683164694019:ios:c300904c9dfe1897004036',
    messagingSenderId: '683164694019',
    projectId: 'project-habit-journal',
    storageBucket: 'project-habit-journal.firebasestorage.app',
    iosBundleId: 'com.example.habitJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTln0auFrTna5CBeCwUUBhmpwNSDU-eCQ',
    appId: '1:683164694019:web:2580636dbbe16237004036',
    messagingSenderId: '683164694019',
    projectId: 'project-habit-journal',
    authDomain: 'project-habit-journal.firebaseapp.com',
    storageBucket: 'project-habit-journal.firebasestorage.app',
    measurementId: 'G-8RM5X2CB2B',
  );
}
